"""Schemas package - Pydantic DTOs for API validation."""
from .doctor import (
    DoctorCreate,
    DoctorResponse,
    DoctorSummary,
    DoctorUpdate,
    ExtractionResponse,
    GenderEnum,
    OnboardingSource,
    PracticeLocationBase,
    QualificationBase,
    ResumeExtractedData,
    TitleEnum,
)
from .onboarding import (
    DoctorDetailsResponse,
    DoctorDetailsUpsert,
    DoctorIdentityCreate,
    DoctorIdentityResponse,
    DoctorMediaCreate,
    DoctorMediaResponse,
    DoctorStatusHistoryCreate,
    DoctorStatusHistoryResponse,
    DoctorWithFullInfoResponse,
    OnboardingStatusEnum,
)
from .voice import (
    CompleteSessionRequest,
    CompleteSessionResponse,
    ConversationMessage,
    ConversationRole,
    ExtractedDataResponse,
    FieldStatus,
    ProcessSpeechRequest,
    ProcessSpeechResponse,
    SessionStatus,
    SessionStatusResponse,
    VoiceSession,
    VoiceSessionCreate,
    VoiceSessionResponse,
)

__all__ = [
    # Doctor schemas
    "DoctorCreate",
    "DoctorResponse",
    "DoctorSummary",
    "DoctorUpdate",
    "ExtractionResponse",
    "GenderEnum",
    "OnboardingSource",
    "PracticeLocationBase",
    "QualificationBase",
    "ResumeExtractedData",
    "TitleEnum",
    # Onboarding schemas
    "DoctorIdentityCreate",
    "DoctorIdentityResponse",
    "DoctorDetailsUpsert",
    "DoctorDetailsResponse",
    "DoctorMediaCreate",
    "DoctorMediaResponse",
    "DoctorStatusHistoryCreate",
    "DoctorStatusHistoryResponse",
    "DoctorWithFullInfoResponse",
    "OnboardingStatusEnum",
    # Voice schemas
    "CompleteSessionRequest",
    "CompleteSessionResponse",
    "ConversationMessage",
    "ConversationRole",
    "ExtractedDataResponse",
    "FieldStatus",
    "ProcessSpeechRequest",
    "ProcessSpeechResponse",
    "SessionStatus",
    "SessionStatusResponse",
    "VoiceSession",
    "VoiceSessionCreate",
    "VoiceSessionResponse",
]
