"""Schemas package - Pydantic DTOs for API validation."""
from .doctor import (
    DoctorCreate,
    DoctorResponse,
    DoctorSummary,
    DoctorUpdate,
    ExtractionResponse,
    GenderEnum,
    OnboardingSource,
    PracticeLocationBase,
    QualificationBase,
    ResumeExtractedData,
    TitleEnum,
)
from .hospital import (
    AffiliationCreate,
    AffiliationCreateWithNewHospital,
    AffiliationResponse,
    AffiliationUpdate,
    AffiliationWithHospitalResponse,
    DoctorPracticeLocationsResponse,
    HospitalCreate,
    HospitalCreateByDoctor,
    HospitalListResponse,
    HospitalMerge,
    HospitalResponse,
    HospitalSearchResult,
    HospitalStats,
    HospitalUpdate,
    HospitalVerificationStatus,
    HospitalVerify,
    PracticeLocationInput,
)
from .onboarding import (
    DoctorDetailsResponse,
    DoctorDetailsUpsert,
    DoctorIdentityCreate,
    DoctorIdentityResponse,
    DoctorMediaCreate,
    DoctorMediaResponse,
    DoctorStatusHistoryCreate,
    DoctorStatusHistoryResponse,
    DoctorWithFullInfoResponse,
    OnboardingStatusEnum,
)
from .testimonial import (
    TestimonialCreate,
    TestimonialListResponse,
    TestimonialResponse,
    TestimonialUpdate,
)
from .voice import (
    CompleteSessionRequest,
    CompleteSessionResponse,
    ConversationMessage,
    ConversationRole,
    ExtractedDataResponse,
    FieldStatus,
    ProcessSpeechRequest,
    ProcessSpeechResponse,
    SessionStatus,
    SessionStatusResponse,
    VoiceSession,
    VoiceSessionCreate,
    VoiceSessionResponse,
)

__all__ = [
    # Doctor schemas
    "DoctorCreate",
    "DoctorResponse",
    "DoctorSummary",
    "DoctorUpdate",
    "ExtractionResponse",
    "GenderEnum",
    "OnboardingSource",
    "PracticeLocationBase",
    "QualificationBase",
    "ResumeExtractedData",
    "TitleEnum",
    # Onboarding schemas
    "DoctorIdentityCreate",
    "DoctorIdentityResponse",
    "DoctorDetailsUpsert",
    "DoctorDetailsResponse",
    "DoctorMediaCreate",
    "DoctorMediaResponse",
    "DoctorStatusHistoryCreate",
    "DoctorStatusHistoryResponse",
    "DoctorWithFullInfoResponse",
    "OnboardingStatusEnum",
    # Voice schemas
    "CompleteSessionRequest",
    "CompleteSessionResponse",
    "ConversationMessage",
    "ConversationRole",
    "ExtractedDataResponse",
    "FieldStatus",
    "ProcessSpeechRequest",
    "ProcessSpeechResponse",
    "SessionStatus",
    "SessionStatusResponse",
    "VoiceSession",
    "VoiceSessionCreate",
    "VoiceSessionResponse",
    # Hospital schemas
    "HospitalCreate",
    "HospitalCreateByDoctor",
    "HospitalUpdate",
    "HospitalVerify",
    "HospitalResponse",
    "HospitalListResponse",
    "HospitalSearchResult",
    "HospitalStats",
    "HospitalVerificationStatus",
    "AffiliationCreate",
    "AffiliationCreateWithNewHospital",
    "AffiliationUpdate",
    "AffiliationResponse",
    "AffiliationWithHospitalResponse",
    "PracticeLocationInput",
    "DoctorPracticeLocationsResponse",
    "HospitalMerge",
    # Testimonial schemas
    "TestimonialCreate",
    "TestimonialUpdate",
    "TestimonialResponse",
    "TestimonialListResponse",
]
